name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install --legacy-peer-deps

      - name: Deploy
        run: |
          git config --global user.name 'LeomaiaJr'
          git config --global user.email 'leomaiajr@hotmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy
